### ISSUE TITLE
error with esm on windows

### ISSUE THREAD

**Issue by amis-shokoohi** [fastify/fastify-autoload#98] opened 2020-08-12 10:21 UTC
I was following @mcollina tutorial for Fastify, and I faced with an error related to fastify-autoload plugin:
```sh
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:781:11)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
    at Loader.import (internal/modules/esm/loader.js:164:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1199:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at loadPlugin (C:\Users\amis\Desktop\fastify3-test\node_modules\fastify-autoload\index.js:117:5)
    at C:\Users\amis\Desktop\fastify3-test\node_modules\fastify-autoload\index.js:27:12
    at Array.map (<anonymous>)
    at fastifyAutoload (C:\Users\amis\Desktop\fastify3-test\node_modules\fastify-autoload\index.js:26:29) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```
I'm running Node v14.7.0 on Windows 10.
This is how the app looks like:
##### app.js
```javascript
import fastify from 'fastify'
import autoload from 'fastify-autoload'
import { join } from 'desm'

export default function (opts) {
    const app = fastify(opts)

    app.register(autoload, {
        dir: join(import.meta.url, 'routes')
    })

    return app
}
```
##### /routes/hello.js
```javascript
export default async function (app) {
    app.get('/', async function (req, rep) {
        return { hello: 'world' }
    })
}
```

**Comment by Eomm** [comment] 2020-08-12 17:30
The join from desm is doing this work?

import { dirname } from 'path'; 
import { fileURLToPath } from 'url'; 

const __dirname = dirname(fileURLToPath(import.meta.url)); ... path.join(__dirname, 'public'))) ...

**Comment by mcollina** [comment] 2020-08-12 18:40
yes, that's the idea

**Comment by amis-shokoohi** [comment] 2020-08-12 19:00
I've actually tried that but still getting the same error.
I also went through `fastify-autoload/index.js` in debug mode, it seemed to work properly.
The problem is with esm. I rewrote it with cjs, it worked. I was just too excited to use esm.

**Comment by fox1t** [comment] 2020-08-13 10:09
This seems the same as this one https://github.com/nodejs/node/issues/31710
Isn't this by design?

**Comment by StarpTech** [comment] 2020-08-13 10:25
How can I help? Will `pathToFileURL` solve the issue?

**Comment by fox1t** [comment] 2020-08-13 10:29
@StarpTech my bad, I am making some test now and `import.meta.url` indeed has already `file://`.

**Comment by fox1t** [comment] 2020-08-13 10:46
@StarpTech if you are a windows user just try to reproduce the issue using the provided `apps.mjs` and `/routes/hello.js`
It would be nice to know that is the `file` value at `https://github.com/fastify/fastify-autoload/blob/f61eb72b9ceccd075cd43be5aa2017aeb5298715/index.js#L117` on windows.

**Comment by StarpTech** [comment] 2020-08-13 11:37
```
console.log(join(import.meta.url, 'routes')); = "D:\repositories\fastify-autoload\route"
```

I could fix it with

fastify-autoloader/index.js
```js
  if (type === 'module') {
    content = await import(url.pathToFileURL(file).href)
  } else {
    content = require(file)
  }
```

app.js
```js
export function dirname(importMeta) {
    return path.dirname(filename(importMeta));
}

export function filename(importMeta) {
    return url.fileURLToPath(importMeta.url);
}

export default function (opts) {
    const app = fastify(opts)

    app.register(autoload, {
        dir: path.join(dirname(import.meta), 'routes')
    })


    return app
}
```

**Comment by fox1t** [comment] 2020-08-13 11:50
Nice, as supposed it worked! Now it would be nice to know why it was missing in the first place. Any clouds @mcollina ?

**Comment by fox1t** [comment] 2020-08-13 12:04
I think that since fastify-plugin handles ESM natively the users doesn't have to use desm package. 🤔

**Comment by amis-shokoohi** [comment] 2020-08-13 12:05
Oh thanks
So passing `C:\...\hello.js` to `import()` rather than `file://C:/.../hello.js` was the problem?

**Comment by mcollina** [comment] 2020-08-13 12:49
> Nice, as supposed it worked! Now it would be nice to know why it was missing in the first place. Any clouds @mcollina ?

No idea. The above code is exactly doing what desm is doing. See

https://github.com/mcollina/desm/blob/master/index.js

**Comment by amis-shokoohi** [comment] 2020-08-13 13:22
Can I steal @StarpTech code and send a PR? 😄

**Comment by mcollina** [comment] 2020-08-13 13:28
sure. I don't 100% understand the problem, but +1

**Comment by StarpTech** [comment] 2020-08-13 14:00
@amis-shokoohi feel free 😄

**Comment by StarpTech** [comment] 2020-08-13 14:03
@mcollina the issue sits not [there](https://github.com/mcollina/desm/blob/master/index.js?rgh-link-date=2020-08-13T12%3A49%3A23Z). We need to pass file URI to `await import()`.

**Comment by mcollina** [comment] 2020-08-13 14:38
why the heck this works on Mac and Linux then? :)

**Comment by StarpTech** [comment] 2020-08-13 14:43
Because in Linux a path is a valid file Uri? 🤔

**Comment by mcollina** [comment] 2020-08-13 15:32
Released as v3.0.8!

**Comment by StarpTech** [comment] 2020-08-13 15:34
Indeed, I tried it with WSL2 on Windows and `/mnt/d/repositories/fastify-autoload/routes/hello.mjs` is a valid file URL 😄 feels like a bug to me in Node.js. It's odd that the API doesn't abstract that behavior.

**Comment by fox1t** [comment] 2020-08-13 15:48
The Node.js parser takes c: part of the Windows paths as protocol. :/

**Comment by mcollina** [comment] 2020-08-13 15:50
@StarpTech can you open an issue on node core on this and tag me on it? Thanks. This is very confusing.

**Closed** 2020-08-13 15:49 UTC
