### ISSUE TITLE
Typescript compiler error when running tests using Vitest

### ISSUE THREAD

**Issue by charklewis** [fastify/fastify-autoload#230] opened 2022-04-19 11:34 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.28.0

### Node.js version

16

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

12.3

### Description

I would like to test my fastify app using [vitest](https://vitest.dev), however I have noticed there is a typescript error I can't seem to get around.

When I run my tests Fastify errors, `fastify-autoload cannot import plugin ... . To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.`. 

I can successfully run the tests when I compile them to Javascript and import the javascript version in the test. This does however, feel a bit hacky. It can also impact the code coverage (depending on how you are generating the javascript). 

### Steps to Reproduce

Stackbliz link: https://stackblitz.com/edit/node-sdwsoh

Run the `npm run test` command. 

### Expected Behavior

Tests can be run in vitest using Typescript without having to compile first, and import the javascript version.

**Comment by guilhermelimak** [comment] 2022-04-29 03:12
Just FYI I worked on this issue for a while and tried solving it by adding a ts-node register call instead of throwing [here](https://github.com/fastify/fastify-autoload/blob/master/index.js#L166), that would handle all require calls for typescript files, transpiling and typechecking them before executing.

I had some typescript errors that I wasn't able to solve. It complained about the file not having exports despite having a default export. I also tried using a named export or using both but the error persisted and it also threw errors regarding missing fastify types that were being imported. I tried multiple settings without success and kinda ran out of options.

I'm also not entirely sure about the performance implications a change like this would have. I assume it probably wouldn't be that bad since it would only affect performance when initializing the plugins, but this should be verified if this approach ends up being used.

**Comment by mcollina** [comment] 2022-04-29 07:46
I think that would be an amazing fix. However ts-node could not be there, so we must catch those error specifically and provide some instructions.
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by simoneb** [comment] 2022-04-29 12:02
We decided to put this on hold because we couldn't come to a solution within a reasonable timeframe, but we may go back to this some time in the future

**Comment by ranyefet** [comment] 2022-05-26 11:16
I'm getting similar error when trying to use `autoload` plugin with [vite-plugin-node](https://github.com/axe-me/vite-plugin-node).

I've created reproducible project [on stackblitz](https://stackblitz.com/edit/node-lxpnpp?file=src/services/health/health.routes.ts).

Is there a way to help resolving this issue as I currently can't use autoload with `vite` + `typescript`

**Comment by ranyefet** [comment] 2022-05-27 06:20
Update, I decided to remove `vite` and `vite-plugin-node` and use other tools to have a fast typescript environment during development.

I've tried `@esbuild-kit/esm-loader` `@swc-node/register` `tsx` and none of them worked. 
At the end I looked at the code for this library and I saw there is a special case for [`tsm`](https://github.com/lukeed/tsm), tried that and it worked perfectly. 

Conclusion: use `node -r tsm ./src/server.ts` and make sure you **don't** have `type: module` in your `package.json`.

**Comment by mcollina** [comment] 2022-05-27 11:04
Unfortunately all those tools needs special handling in this library to work :(. I don't know if there is a way to handle it otherwise.

PRs are welcomed!

**Comment by ranyefet** [comment] 2022-05-27 11:14
Can you explain why each tool need different handling?
As I understand these tools transpile modules on the fly from `ts` to `js`. 
After that step everything should work the same, no?

**Comment by mcollina** [comment] 2022-05-27 18:08
Unfortunately their ways of doing things is different, specifically when targeting ESM.

**Comment by climba03003** [comment] 2022-09-02 06:17
Reopen due to 6adc2966ba5f9414139af22033eb78b3cb0c1f91

**Comment by kylerush** [comment] 2022-09-08 19:41
Just now seeing that the vitest ts-node pr broke things mentioned in #266. Will take a look at that tomorrow and hopefully have a PR next week.

**Comment by alrramezani** [comment] 2022-09-10 19:39
I have the same issue with jest global setup, when I use autoload in globalSetup.ts I got the same error

> fastify-autoload cannot import plugin ... . To fix this error compile TypeScript to JavaScript or use 'ts-node' to run your app.

**Comment by kylerush** [comment] 2022-09-13 18:01
There's some active conversation about this in a vitest issue here: https://github.com/vitest-dev/vitest/issues/2028

I think getting `autoload` to actually run in vitest again will not be hard, but the problem I ran into is the code coverage from vitest is very whacky when using `autoload` because vitest is not aware of the files that `autoload` loads. To me this makes vitest not a workable solution so I'm hoping we can figure out a solution with some of the vitest contributors 🤞

**Comment by kylerush** [comment] 2022-09-13 18:06
@alrramezani - If you use version 5.3.0 of `autoload` your Jest tests should work. You can see that working here: https://github.com/kylerush/vitest-v-tap

**Comment by jclaessens97** [comment] 2022-10-11 08:01
While setting up a repro for a "vitest alias" issue, I came across different kind of issues I never came across with my main app. One of the things is getting `@fastify/auto-load` to work. For now I got it working with following versions (and no additional config):

```
  "dependencies": {
    "@fastify/autoload": "5.3.0",
    "@fastify/cors": "^8.1.0",
    "@fastify/env": "^4.1.0",
    "@prisma/client": "^4.4.0",
    "@trpc/server": "10.0.0-proxy-beta.15",
    "fastify-plugin": "^4.2.1",
    "fastify": "^4.8.1",
    "zod": "^3.19.1"
  },
  "devDependencies": {
    "@trpc/client": "10.0.0-proxy-beta.15",
    "@types/node": "^18.8.4",
    "cross-env": "^7.0.3",
    "dotenv-cli": "^6.0.0",
    "esbuild": "^0.15.10",
    "esbuild-plugin-pino": "1.2.4",
    "fastify-tsconfig": "^1.0.1",
    "pino": "^8.6.1",
    "pino-pretty": "^9.1.1",
    "prisma": "^4.4.0",
    "tiny-glob": "^0.2.9",
    "tsx": "^3.10.1",
    "typescript": "^4.8.4",
    "vitest": "^0.24.1",
    "ts-node": "^10.9.1"
  },
  ```
  
  Somehow, for my main app I have the same versions, except no `ts-node` explicitly installed 🤔

**Comment by jclaessens97** [comment] 2022-10-12 09:10
After some investigation it also seems that `@fastify/autoload` is overriding the `alias` config of `vitest`. I'm currently using `5.3.0` since it's the only version I come close to get it working. 

I understand that code coverage should be working, but I'm not sure if it should be blocking to make `@fastify/autoload` work with vitest again? @kylerush 

I'm willing to help wherever I can to resolve this issue.

**Comment by Uzlopak** [comment] 2022-10-12 10:22
You just need a way to detect if you are running vitest. Like a set environment variable or so. Compare with #271

**Comment by jclaessens97** [comment] 2022-10-12 10:27
`process.env.VITEST_MODE` and check if it's set or not? 

But even then further down it results in some issues because the use of require or that the imported ".ts" files are not recognized.

**Comment by climba03003** [comment] 2022-10-12 10:29
> But even then further down it results in some issues because the use of require or that the imported ".ts" files are not recognized.

You can force to use `import` if it does matter by `vitest`. And `@fastify/autoload` do nothing on the file path, it just call either `import` or `require`. It means that `vitest` just don't work with it somehow.

https://github.com/fastify/fastify-autoload/blob/master/index.js#L239-L241

**Comment by jclaessens97** [comment] 2022-10-12 11:15
Yeah so I tried that.

I added a `const isVitestEnvironment = process.env.VITEST_MODE !== undefined`, added it to the `typescriptSupport` and then on those lines you highlighted I also added the check if it's `vitest` to use the `await import`, but then I'm getting errors like `Error: unknown file extension ".ts"` for the plugins folder (e.g. `cors.ts`, `env.ts`, ... in my repro). 

I also gave `import.meta.url` a shot as i've seen it being used by vite in a vue 3 context, but then it complains that it's not being used inside a ESM environment (thus `package.json` doesn't contain `type: "module"`

For now I'm just "working around" it by not using `@fastify/autoload` and no aliases.

**Comment by Uzlopak** [comment] 2022-10-12 11:35
I have a potential PR

**Comment by Uzlopak** [comment] 2022-10-12 12:02
I quite dont understand now the issue you meant?!

see #273

**Comment by Uzlopak** [comment] 2022-10-12 12:28
Provided an alternative approach to set forceESM instead of ts-node #274

**Comment by Uzlopak** [comment] 2022-10-12 14:07
You could test it by setting the repo and the branch for the package in package.json

```json
{
  "dependencies": {
   ...
    "@fastify/autoload": "fastify/fastify-autoload#forceESM-for-vitest"
   ...
  }
}
```

**Comment by Uzlopak** [comment] 2022-10-12 15:14
@jclaessens97 

If it works, than please give feedback to have higher confidence that the PR solves the issue in a real environment.

**Comment by jclaessens97** [comment] 2022-10-13 07:42
I didn't have the time yesterday to check, but I do have time today, if it's still needed?

**Comment by Uzlopak** [comment] 2022-10-13 08:04
we released today the new version ;)

**Comment by jclaessens97** [comment] 2022-10-14 09:40
Might be a config issue on my side, but when I now try my repro again (with the updated package), I get the following:

```
TypeError: Unknown file extension ".ts" for /Users/jclaessens/dev/github/vitest-alias-repro/packages/api/src/plugins/cors.ts
Serialized Error: {
  "code": "ERR_UNKNOWN_FILE_EXTENSION",
}
```

This is the same issue I got when I tried to do the changes myself.

Again, it might be a config issue on my side, but it's unclear to me at this point.

**Comment by jclaessens97** [comment] 2022-10-14 09:55
I know, but what causes `vitest` to throw it? It's not only with this package btw. I'm also using `awilix` and there it's the same.

**Comment by climba03003** [comment] 2022-10-14 09:58
It would be better if you can provide a minimal repro without `docker` and `pnpm workspace`.
I cannot run an environment with those tools.

**Comment by jclaessens97** [comment] 2022-10-14 09:58
You can try out my repro: https://github.com/jclaessens97/vitest-alias-repro

**Comment by jclaessens97** [comment] 2022-10-14 10:06
You can find a simplified repro here: https://github.com/jclaessens97/vitest-alias-repro-simplified

**Comment by jclaessens97** [comment] 2022-10-14 13:53
> I know, but what causes `vitest` to throw it? It's not only with this package btw. I'm also using `awilix` and there it's the same.

In `awilix` it seemed it was just an issue with using `.ts` and `.js` files when using glob expressions to import modules. When changing to a way where I'm just importing these modules manually, that issue is solved for me. 

However for an autoloader I assume there is no such way as hardcoding these imports so there should be another way 🤔 

For reference: https://github.com/jeffijoe/awilix/issues/300

**Comment by simitch1** [comment] 2022-12-05 14:59
Hi guys, sorry if I bother you.
I'm still having the same ts error while trying to setup vitest in a normal fastify + ts + fastify autoload setup.
Is the fix already released? I have to do some additional configuration to make it works?
If needed I could try to investigate the problem but I'm new to fastify :)
Thank you

**Comment by Uzlopak** [comment] 2022-12-05 15:01
It should work out of the box. But maybe you can provide a minimal viable code example. Like git repo, which we can clone.

**Comment by simitch1** [comment] 2022-12-05 16:00
> It should work out of the box. But maybe you can provide a minimal viable code example. Like git repo, which we can clone.

Hi Uzlopak, thanks for the reply and your help.
I tried to setup a simple repository similar to the one I'm using for the real project; https://github.com/simitch1/vitest-fastify-repro

Hope is not a config issue...

**Comment by lxghtless** [comment] 2023-02-03 04:11
> 

this worked for me

**Comment by lxghtless** [comment] 2023-02-03 04:11
> This looks like a really hard thing to solve, and I think the problem lies between `vite` and `node`. I couldn't think of a way to add support for this edge case... Anyway, I created a simple workaround that toggles between `vitest` support.
> 
> 1. **Install `cjstoesm`:**
> 
> ```shell
> npm i -D cjstoesm
> ```
> 
> 2. **In your `./package.json` add scripts:**
> 
> ```json
> "scripts": {
>   "pretest": "node ./test/vitest.js on",
>   "test": "vitest",
>   "posttest": "node ./test/vitest.js off",
> }
> ```
> 
> 3. **Create `./test/vitest.js` with this code:**
> 
> ```js
> const fs = require("fs");
> const path = require("path");
> const { transform } = require("cjstoesm");
> 
> const autoloadPath = "node_modules/@fastify/autoload";
> const indexJs = "index.js";
> const indexTs = "index.ts";
> 
> main();
> 
> function main() {
>   const [state] = process.argv.slice(2);
>   changePackageType(state === "on");
>   convertToESM();
> }
> 
> function changePackageType(isOn = false) {
>   const packagePath = path.join(autoloadPath, "package.json");
>   const packageFile = fs.readFileSync(packagePath, "utf8");
>   const updatedPackageFile = packageFile.replace(
>     `"main": "${isOn ? indexJs : indexTs}"`,
>     `"main": "${isOn ? indexTs : indexJs}"`
>   );
>   fs.writeFileSync(packagePath, updatedPackageFile);
> }
> 
> async function convertToESM() {
>   const indexTsPath = path.join(autoloadPath, indexTs);
>   if (fs.existsSync(indexTsPath)) {
>     return;
>   }
>   const result = await transform({
>     input: path.join(autoloadPath, indexJs),
>     write: false,
>   });
>   for (const { fileName, text } of result.files) {
>     fs.writeFileSync(indexTsPath, text);
>   }
> }
> ```
> 
> 4. **Run the tests**
> 
> ```shell
> npm run test
> ```
> 
> For now it's the only thing we can do, let me know if this works for you.

this worked for me

**Comment by clabnet** [comment] 2023-02-03 16:26
@Pustinyak Your solution work for me. Thank's

**Comment by jimmy-guzman** [comment] 2023-02-28 21:51
@Pustinyak solution worked for me. And based off this solution another solution that worked for me, was to simply leverage [vitest's deps](https://vitest.dev/config/#deps) option, ie
```ts
export default defineConfig({
  test: {
    deps: {
      inline: ["@fastify/autoload"],
    },
  },
});
```

**Comment by bodinsamuel** [comment] 2023-04-02 17:48
Hey, 
None of the solution worked for me. 
I had to remove `'@fastify/autoload'` and loads the plugins myself 🫣

**Comment by Sophoniiee** [comment] 2023-04-25 17:13
> 

Same for me 😢

**Comment by Sophoniiee** [comment] 2023-04-25 17:14
> Hey,
> None of the solution worked for me.
> I had to remove `'@fastify/autoload'` and loads the plugins myself 🫣
Same for me 😢

**Comment by tompahoward** [comment] 2023-05-22 04:25
> @Pustinyak solution worked for me. And based off this solution another solution that worked for me, was to simply leverage [vitest's deps](https://vitest.dev/config/#deps) option, ie
> 
> ```ts
> export default defineConfig({
>   test: {
>     deps: {
>       inline: ["@fastify/autoload"],
>     },
>   },
> });
> ```

Under-rated solution. 

Literally, with a documentation update, this issue could be closed 👏👏👏

**Comment by Uzlopak** [comment] 2023-05-22 05:58
It seems that latest vitest version passes our unit tests after failing for some weeks.

#312

**Comment by Uzlopak** [comment] 2023-08-03 15:37
Thank you.  :)

**Closed by Uzlopak** 2023-08-03 15:37 UTC
Labels: feature request

**Comment by vtyagunov** [comment] 2023-10-02 10:49
This is somehow still reproducible with @fastify/auto-load 5.7.1 and vitest 0.34.5.

Running `npx vitest run` with no vitest.config.ts file gives the `TypeError: Unknown file extension ".ts" ` error.

**Comment by rrcabrera9625** [comment] 2024-01-15 20:55
`deps.inline` is now deprecated, and `deps.optimizer` should be used instead. I can't get it to work with `deps.optimizer`, any suggestions? I tried using `server.deps.inline` and it works, but the ideal would be to stop using `server.deps.inline` completely as it is the intention mentioned in: https://github.com/vitest-dev/vitest/releases/tag/v0.34.0.

**Comment by lisez** [comment] 2025-10-31 03:24
> [@Pustinyak](https://github.com/Pustinyak) solution worked for me. And based off this solution another solution that worked for me, was to simply leverage [vitest's deps](https://vitest.dev/config/#deps) option, ie
> 
> export default defineConfig({
>   test: {
>     deps: {
>       inline: ["@fastify/autoload"],
>     },
>   },
> });

> `deps.inline` is now deprecated, and `deps.optimizer` should be used instead. I can't get it to work with `deps.optimizer`, any suggestions [@jimmy-guzman](https://github.com/jimmy-guzman) ? I tried using `server.deps.inline` and it works, but the ideal would be to stop using `server.deps.inline` completely as it is the intention mentioned in: https://github.com/vitest-dev/vitest/releases/tag/v0.34.0.

For anyone looking for a drop-in replacement configuration in Vitest 4:

```typescript
export default defineConfig(() => ({
  test: {
    server: {
      deps: {
        inline: ['@fastify/autoload'],
      },
    },
  },
}));
```

reference: https://vitest.dev/config/#server-deps-inline

**Comment by melroy89** [comment] 2026-02-10 00:56
> reference: https://vitest.dev/config/#server-deps-inline

New link: https://vitest.dev/config/server.html#inline
