### ISSUE TITLE
Confusing example, auto prefixing

### ISSUE THREAD

**Issue by Extarys** [fastify/fastify-autoload#59] opened 2019-12-31 00:42 UTC
## 💬 Questions and Help
In the README there is the following example:
```
// index.js
fastify.register(AutoLoad, {
  dir: path.join(__dirname, 'services'),
  options: {}
})

// /services/items/get.js
module.exports = function (f, opts, next) {
  f.get('/:id', (request, reply) => {
    reply.send({ answer: 42 })
  })

  next()
}

// /services/items/list.js
module.exports = function (f, opts, next) {
  f.get('/', (request, reply) => {
    reply.send([0, 1, 2])
  })

  next()
}
```

My test:
**index.ts**
```
server.register(AutoLoad, {
	dir: path.join(__dirname, 'modules/routes/v1'),
	options: { prefix: '/v1' },
	includeTypeScript: true
})
```
**modules/routes/v1/domains/index.ts**
```
module.exports = (server, opts, next) => {
	server.route({
		url: "/:url",
		logLevel: "warn",
		method: ["GET"],
		schema: {
			params: {
				id: { type: 'string', maxLength: 2 },
			},
			response: {}
		},
		handler: async (request, reply) => {
			return reply.send({ url: request.params.id, works: true });
		}
	});
	next();
};
```
Generated route:
`GET     /v1/:url`

Looking at the README, I was under the impression that this would load routes using the directories path. Am I doing something wrong or I interpreted that the wrong way?

I removed the fastify-plugin route and converted it to a more standard one, but it didn't change anything it seems.

**Comment by mcollina** [comment] 2019-12-31 15:33
Can you try without typescript? I fear it might be related to that.

**Comment by Extarys** [comment] 2019-12-31 18:27
I created another project for testing.

index.js:
```
var path = require('path')
var fastify = require('fastify')
var autoload = require('fastify-autoload')
var blipp = require('fastify-blipp')

const server = fastify({
	logger: true
});

console.log(__dirname)
server.register(autoload, {
	dir: path.join(__dirname, 'v1'),
	options: { prefix: '/v1' }
})
server.register(blipp)

server.post("/hello", async (req, reply) => ({
  greeting: `Hello, ${req.body.username}`
}));


const start = async () => {
	try {
		await server.listen(3001, "127.0.0.1");
		server.blipp();
	} catch (err) {
		console.log(err);
		server.log.error(err);
		process.exit(1);
	}
};

process.on("uncaughtException", error => {
	console.error(error);
});
process.on("unhandledRejection", error => {
	console.error(error);
});

start();
```

v1/index.js:
```
module.exports = (server, opts, next) => {
	server.route({
		url: "/:id",
		logLevel: "warn",
		method: ["GET"],
		schema: {
			params: {
				id: { type: 'string', maxLength: 20 },
			},
			response: {}
		},
		handler: async function (request, reply) {
			return reply.send({ id: request.params.id, works: true });
		}
	});
	next();
};
```
v1/test/index.js: Same as above

Routes should be:
```
/hello
/v1:id
/v1/test/:id
```

But it result in an error as the two routes have the same path.
Manually setting the test route with `test/:id` works, but blipp doesn't catch it, only the route defined in the main file is shown (/hello).

On the first post some of my folders have no js in them, only in the subfolders, maybe it make the autoload plugin confused. I'll continue to play with it, but still, according to the example, the paths should be generated.

**Comment by mcollina** [comment] 2020-01-01 08:05
The issue is caused by directories without any js files, would you like to send a PR to fix this?

See https://github.com/fastify/fastify-autoload/blob/2deb5f00eb4ab6e8a6a16cac23983ca0f8f21443/index.js#L78.

**Comment by Extarys** [comment] 2020-01-01 18:31
Good catch! I created another test project, based on the example above and it works.

![image](https://user-images.githubusercontent.com/11581433/71644714-efeb9180-2c9a-11ea-83f6-cadb267985db.png)
![image](https://user-images.githubusercontent.com/11581433/71644715-f5e17280-2c9a-11ea-8d4d-3bee18af6661.png)

So it should work. I'll try and rethink my project structure and not naming my route files `index` :stuck_out_tongue:

**Comment by mcollina** [comment] 2020-07-15 14:20
closed in https://github.com/fastify/fastify-autoload/pull/87

**Closed by mcollina** 2020-07-15 14:20 UTC
Labels: bug, good first issue
