### ISSUE TITLE
fastify-cli, fastify-autoload Duplicate plugin: anonymous

### ISSUE THREAD

**Issue by jerrythomas** [fastify/fastify-autoload#73] opened 2020-04-18 02:49 UTC
#### You have already researched for similiar issues?
Yes. It doesn't seem to have been reported

#### What are you trying to achieve or the steps to reproduce?

Create a new project using fastify-cli and add a new plugin under the plugins directory.

```bash
fastify generate new-project
npm test
npm start
```

Duplicate plugins/support.js and name it as new_support.js. Change the decorated function name to someOtherSupport.

#### What was the result you received?
`npm test` fails with error "Duplicate plugin: anonymous". However, `npm start` does not cause any error. 

When running tests, it seems like the plugin name is 'anonymous', but when running the app it takes the name of the file.

#### What did you expect?

Tests should behave same way as application start.

#### Context

* *node version*:  v13.12.0
* *fastify version*: 1.5.0
* *os*: Mac
* *any other relevant information*:

**Comment by Eomm** [comment] 2020-05-01 09:08
> It seems auto load is a bit dumb, this is worth a fix.

Transferred issue and labelled 👍

**Comment by lundibundi** [comment] 2020-06-22 15:54
The newest version of fastify (v3) + fastify-autoload (v3) needs this example https://github.com/jerrythomas/fastify-dup-plugin-err to change the route of `example` to `fastify.get('/', function routeFn(request, reply) {` (as newest fastify auto-prefixes routes) and everything will work as intended.

**Comment by salmanm** [comment] 2021-01-19 14:51
This seems to have resolved in autoload v3

**Closed by salmanm** 2021-01-19 14:51 UTC
Labels: bug, good first issue
